# Site settings
title: Catherine Kwak
email: catherine.webdev@gmail.com
description: A web development portfolio and blog
baseurl: ""
url: "http://catherinekwak.com"

# Social links
social-links:
 - title: GitHub
   url: https://github.com/khopsickle
   class: github
 - title: LinkedIn
   url: https://www.linkedin.com/in/catherinekwak
   class: linkedin
 - title: Twitter
   url: https://twitter.com/khopsickle
   class: twitter

# Build settings
markdown: kramdown
highlighter: pygments
encoding: utf-8
sass:
  style: compressed